export const drugs = {
  Adenosine: {
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 3,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Adrenaline: {
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 1,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Atropine: {
    dose: 0.02,
    dosage: "mg/kg",
    dissolve: 1,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Fentanyl: {
    dose: 1,
    dosage: "mcg/kg",
    dissolve: 50,
    dissolveUnit: "mcg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Ketamine: {
    dose: 1,
    dosage: "mg/kg",
    dissolve: 50,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Vecuronium: {
    dose: 0.01,
    dosage: "mg/kg",
    dissolve: 10,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
  },
  Succinilcolina: {
    dose: 1,
    dosage: "mg/kg",
    dissolve: 50,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
  },
  Lorazepam: {
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 4,
    dilute: 1,
    diluteUnit: "ml",
    indication: "No dilution needed. Take",
  },
  Midazolam: {
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 5,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Morphine: {
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 10,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  Flumazenil: {
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 0.5,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "No dilution needed. Take",
  },
};
