export const drugs = [
  {
    drug: "Adenosine",
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 3,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Adrenaline",
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 1,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Atropine", 
    dose: 0.02,
    dosage: "mg/kg",
    dissolve: 1,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Fentanyl", 
    dose: 1,
    dosage: "mcg/kg",
    dissolve: 50,
    dissolveUnit: "mcg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Ketamine",
    dose: 1,
    dosage: "mg/kg",
    dissolve: 50,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Vecuronium", 
    dose: 0.01,
    dosage: "mg/kg",
    dissolve: 10,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
  },
  {
    drug: "Succinilcolina",
    dose: 1,
    dosage: "mg/kg",
    dissolve: 50,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
  },
  {
    drug: "Lorazepam",
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 4,
    dilute: 1,
    diluteUnit: "ml",
    indication: "No dilution needed. Take",
  },
  {
    drug: "Midazolam",
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 5,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Morphine",
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 10,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Prepare",
  },
  {
    drug: "Flumazenil",
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 0.5,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "No dilution needed. Take",
  },
];
