export const drugs = [
  {
    drug: "Adenosine",
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 3,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/4gnRP92/adenosine.jpg",
  },
  {
    drug: "Adrenalin",
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 1,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/bKKL84P/adrenalin.jpg",
  },
  {
    drug: "Atropine",
    dose: 0.02,
    dosage: "mg/kg",
    dissolve: 1,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/f8JmMGz/atropine.jpg",
  },
  {
    drug: "Fentanyl",
    dose: 1,
    dosage: "mcg/kg",
    dissolve: 50,
    dissolveUnit: "mcg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Mix and stir",
    imageURL: "https://i.ibb.co/chdPRVv/fentanyl.jpg",
  },
  {
    drug: "Ketamine",
    dose: 1,
    dosage: "mg/kg",
    dissolve: 50,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/V99ZSPT/ketamine.jpg",
  },
  {
    drug: "Vecuronium",
    dose: 0.01,
    dosage: "mg/kg",
    dissolve: 10,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/MGHqD2L/vecuronium.jpg",
  },
  {
    drug: "Succinylcholine",
    dose: 1,
    dosage: "mg/kg",
    dissolve: 50,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/5sMh0kk/succinylcholine.jpg",
  },
  {
    drug: "Lorazepam",
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 4,
    dissolveUnit: "ml",
    dilute: 1,
    diluteUnit: "ml",
    indication: "No dilution needed. Take",
    imageURL: "https://i.ibb.co/VMwhB5f/lorazepam.jpg",
  },
  {
    drug: "Midazolam",
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 5,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/7yhHMKD/midazolam.jpg",
  },
  {
    drug: "Morphine",
    dose: 0.1,
    dosage: "mg/kg",
    dissolve: 10,
    dissolveUnit: "mg",
    dilute: 10,
    diluteUnit: "ml",
    indication: "Dilute",
    imageURL: "https://i.ibb.co/BwjryQM/morphine.jpg",
  },
  {
    drug: "Flumazenil",
    dose: 0.1,
    dosage: "ml/kg",
    dissolve: 0.5,
    dissolveUnit: "mg",
    dilute: 5,
    diluteUnit: "ml",
    indication: "No dilution needed. Take",
    imageURL: "https://i.ibb.co/3ktRywR/flumazenil.jpg",
  },
];
