import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  listColumn: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  searchBar: {
    marginTop: 15,
    borderColor: "#C4C4C4",
    borderWidth: 3,
    height: 40,
    borderRadius: 40,
    width: 300,
  },
  blackBoldText: {
    fontWeight: "bold",
  },
  whiteBoldText: {
    fontWeight: "bold",
    color: "white",
  },
  btrText: {
    color: "#C4C4C4",
    fontSize: 16,
    marginLeft: 5,
  },
  searchBarContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  screen: {
    paddingTop: 62,
    backgroundColor: "white",
    flex: 1,
  },
  doseText: {
    fontFamily: "Roboto",
    fontWeight: "bold",
    color: "white",
    fontSize: 26,
    alignContent: "center",
    marginLeft: 118,
  },
  doseTextDefault: {
    fontFamily: "Roboto",
    fontWeight: "bold",
    color: "white",
    fontSize: 26,
    alignContent: "center",
    marginLeft: 0,
  },
  upperBar: {
    height: 50,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#96EAEF",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  upperBarDefault: {
    height: 50,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#96EAEF",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  input: {
    borderBottomColor: "black",
    borderBottomWidth: 1,
    width: 170,
    marginLeft: 5,
  },
  nameError: {
    color: "red",
    fontWeight: "bold",
    marginTop: 10,
  },
  genderError: {
    color: "red",
    fontWeight: "bold",
    marginBottom: 10,
  },
  items: {
    marginTop: 80,
  },
  item: {
    padding: 10,
    marginTop: 5,
    marginBottom: 5,
    width: 300,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderColor: "#C4C4C4",
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: "white",
    borderTopWidth: 5,
    borderTopColor: "#96EAEF",
  },
  itemFemale: {
    padding: 10,
    marginTop: 5,
    marginBottom: 5,
    width: 300,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderColor: "#C4C4C4",
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: "white",
    borderTopWidth: 5,
    borderTopColor: "#FAA7F6",
  },
  checkBoxes: {
    marginTop: 10,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  checkBox: {
    margin: 0,
    padding: 0,
  },
  addButtonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },

  addButton: {
    backgroundColor: "#BB22B5",
    height: 30,
    width: 120,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  headline: {
    fontFamily: "pinyon-script-regular",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 18,
    marginTop: 15,
    width: 350,
    color: "#C4C4C4",
  },
  headlineBottom: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 18,
    marginTop: 0,
    width: 350,
    color: "#C4C4C4",
  },
  bottomShadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  safeAreaView: {
    backgroundColor: "white",
    flex: 1,
  },
  pickersView: {
    flex: 1,
    alignItems: "center",
    marginTop: 15,
  },
  pickersBox: {
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "#C4C4C4",
    width: "80%",
    height: 50,
  },
  pickersBoxPink: {
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "#BB22B5",
    width: "80%",
    height: 50,
  },
  noRecordsMessage: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  deleteCloseStyle: {
    marginLeft: 220,
  },
  patientName: {
    color: "#C4C4C4",
    fontWeight: "bold",
    fontSize: 14,
    alignSelf: "center",
  },
  pickerBox: {
    flex: 1,
    alignSelf: "center",
    textAlign: "center",
    justifyContent: "center",
    width: "100%",
  },
  formLabel: {
    marginTop: 15,
    alignSelf: "flex-start",
    marginLeft: "10%",
    color: "#C4C4C4",
  },
  formLabelPink: {
    marginTop: 15,
    alignSelf: "flex-start",
    marginLeft: "10%",
    color: "#BB22B5",
  },
  drugLabel: {
    alignSelf: "flex-start",
    marginLeft: "10%",
    color: "#C4C4C4",
  },
  drugLabelPink: {
    alignSelf: "flex-start",
    marginLeft: "10%",
    color: "#BB22B5",
  },
  banner: {
    width: "100%",
    height: 35,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    backgroundColor: "#96EAEF",
    marginTop: 30,
  },
  bannerOff: {
    width: "100%",
    height: 35,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    backgroundColor: "#c4c4c4",
    marginTop: 30,
  },
  switchTextContainer: {
    marginLeft: 20,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
  },
  bannerText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 5,
  },
  backToRecords: {
    marginTop: 10,
    marginLeft: 5,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
  }
});
